# Mapping Atlas → proxies FP-Qubit Design
# Version: 0.1.0
# Source: biological-qubits-atlas (commit abd6a4cd7dde94dc4ca7cde69aee3fad25757bcf)

# Proxies photophysiques pour protéines fluorescentes
proxies:
  # Lifetime = durée de vie de l'état excité (ns)
  # Proxy potentiel: colonnes lifetime, Quantum_yield (notes)
  lifetime:
    atlas_columns: ["Photophysique"]  # Champ texte avec "lifetime_X.Xns"
    notes: "Extraire valeur lifetime depuis champ Photophysique (parsing requis)"
    target_range: [1.0, 5.0]  # ns (typique FP)
    
  # Contraste = contraste optique (%)
  contrast:
    atlas_columns: ["Contraste_%"]
    notes: "Contraste ODMR/ESR adapté comme proxy pour contraste optique"
    target_range: [10, 30]  # %
    
  # Température de fonctionnement (K)
  temperature:
    atlas_columns: ["Temperature_K"]
    notes: "Privilégier systèmes stables à 295-310 K (conditions physio)"
    target_range: [295, 310]  # K
    
  # Méthode de lecture
  method:
    atlas_columns: ["Methode_lecture"]
    notes: "Focus sur systèmes Optical-only ou ODMR (compatibles FP)"
    
  # Contexte biologique
  context:
    atlas_columns: ["Hote_contexte"]
    notes: "Privilégier in_cellulo, in_vivo confirmés"

# Filtres de sélection
filters:
  only_room_temperature: true       # Garder seulement T > 290 K
  exclude_indirect: true            # Exclure Methode_lecture = "Indirect"
  min_verification: "verifie"       # Garder seulement Verification_statut = "verifie"
  exclude_toxic: true               # Exclure Cytotox_flag = 1
  min_quality: 2                    # Qualite >= 2

# Colonnes manquantes identifiées (TODO)
missing_columns:
  - "Quantum_yield"     # Pas de colonne dédiée, dans champ texte Photophysique
  - "ISC_rate"          # Taux de croisement intersystème (pas dans Atlas)
  - "Photostability"    # Mentionné en texte (Limitations, Notes) mais pas quantitatif

# Actions requises
todos:
  - "Parser champ Photophysique pour extraire lifetime, QY, em/ex"
  - "Définir fonction de score multi-objectif (lifetime + contrast + T_stability)"
  - "Valider mapping avec 5-10 systèmes Atlas classe A/B"



