name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 src/ scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings (relaxed for skeleton)
        flake8 src/ scripts/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test imports
      run: |
        python -c "import sys; sys.path.insert(0, 'src'); import fpqubit; print('fpqubit imported successfully')"
        python -c "import sys; sys.path.insert(0, 'src'); from fpqubit.utils.seed import set_seed; print('seed module OK')"
        python -c "import sys; sys.path.insert(0, 'src'); from fpqubit.utils.io import read_csv; print('io module OK')"
    
    - name: Check scripts run (dry-run)
      run: |
        python scripts/train_baseline.py --config configs/example.yaml || echo "Script skeleton (expected)"
        python scripts/generate_mutants.py --config configs/example.yaml || echo "Script skeleton (expected)"

