name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Copy shortlist from outputs to site
      run: |
        if [ -f outputs/shortlist.csv ]; then
          cp outputs/shortlist.csv site/shortlist.csv
          echo "Copied outputs/shortlist.csv to site/"
        else
          echo "Warning: outputs/shortlist.csv not found, using existing site/shortlist.csv"
        fi
      shell: bash
    
    - name: Setup Pages
      uses: actions/configure-pages@v3
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './site'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

