name: repro-minimal

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ docs/repro-hardening-v2.2.2 ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Validate CV metrics
        run: |
          python scripts/eval_cv_metrics.py
